#!/bin/sh

cd "$HOME"

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file "$HOME/Brewfile"
  fi
  
  if ! command -v node >/dev/null 2>&1; then
    echo "Installing node.js"
    nvm install --lts
  fi


fi
