live_config_reload = true

[env]
TERM = "xterm-256color"


[window]
decorations = "buttonless"
dynamic_padding = true 
opacity = 0.9

[font]
size = 14.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Medium Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Medium"
